services:
  - type: web
    name: ai-code-reviewer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai.reviewer:app
    plan: free
    branch: master
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyByjtOi44YnHbJ4SpWqW0wfNXljdzqJRPw
      - key: PYTHON_VERSION
        value: 3.9